part of constants;

class Strings {
  static const String ADD = 'Dodaj',
      ABOUT = 'O programie',
      ADD_TO_TRANSPORT = 'Dodaj do transportu',
      AMMO = 'Amunicja',
      BOMB = 'Bomba',
      BOX = 'Pojemnik',
      CAPACITY = 'Pojemność',
      CAR = 'Pojazd',
      CAR_NAME = 'Nazwa pojazdu',
      CAR_NUMBER = 'Numer pojazdu',
      CLOSE = 'Zamknij',
      COMPATIBILITY_GROUP = 'Grupa kompatybilności',
      CONTAINER_FULLY_LOADED_GROSS_WEIGHT =
          'Waga brutto załadowanego kontenera',
      CONTAINER_FULLY_LOADED_NEW =
          'Waga środków wybuchowych załadowanego kontenera',
      CONTAINER_NAME = 'Nazwa kontenera',
      CONTAINER_NET_WEIGHT = 'Waga netto kontenera',
      COUNT = 'Przelicz',
      ENTER_NUMBER_OF_BAA = 'Podaj ilość środków',
      EXPLOSION_CLASS = 'Klasa wybuchowości',
      EXPLOSION_SUBCLASS = 'Podklasa wybuchowości',
      GROSS_WEIGHT = 'Waga brutto',
      HINT = 'Podpowiedź',
      HINT_NET_WEIGHT =
          'Waga netto - to łączna waga środków bojowych bez opakowania.',
      HINT_GROSS_WEIGHT =
          'Waga brutto - to łączna waga środków bojowych wraz z opakowaniami.',
      HEIGHT = 'Wysokość',
      HEXOGEN_EQUIVALENT = "Równoznacznik heksogenowy",
      INFORMATION = 'Informacje',
      NUMBER_OF_INCOMPLETE_BOXES = 'Liczba niepełnych kontenerów',
      LENGTH = 'Długość',
      LOAD_WEIGHT = 'Waga ładunku',
      LOADED_CARGO_PARAMETERS = 'Parametry załadowanego ładunku',
      PARAMETERS_OF_THE_LOADING_AREA = 'Parametry powierzchni załadunkowej',
      PERMISSIBLE_NEW = 'Dopuszczalna waga ładunku wybuchowego',
      PERMISSIBLE_WEIGHT = 'Dopuszczalna waga',
      PCS = 'szt.',
      PYROTECHNIC = 'Pirotechnika',
      ROCKET = 'Pocisk rakietowy',
      MAX_STACK_HEIGHT_DURING_TRANSPORT =
          'Maksymalna wysokość stosu w trakcie transportu',
      MAX_STACK_LEVEL = 'Maksymalny poziom stosu',
      MAX_WAREHOUSE_STACK_LEVEL = 'Maksymalny poziom stosu w czasie magazynowania',
      NAME = 'Nazwa',
      NAME_OF_THE_CAR = 'Nazwa pojazdu',
      NEW = 'Waga ładunków wybuchowych',
      NET_WEIGHT = 'Waga netto',
      NO = 'NIE',
      NUMBER_OF_CHOSEN_BAA = 'Ilość wybranych środków',
      NUMBER_OF_THE_BAA = 'Ilość środków',
      NUMBER_OF_CARS = 'Ilość pojazdów',
      NUMBER_OF_THE_CONTAINERS = 'Ilość kontenerów',
      NUMBER_OF_THE_STACKS = 'Ilość stosów',
      NUMBER_OF_STACK_LEVELS = 'Ilość poziomów stosu',
      SETTINGS = 'Ustawienia',
      STACK = 'Stos',
      STACKS_LEVEL = 'Poziomy stosu',
      STACK_LEVEL = 'Poziom stosu',
      TRANSPORT = 'Transport',
      TRANSPORT_NAME = 'Nazwa transportowa',
      WIDTH = 'Szerokość',
      UN_CODE = 'Cod UN',
      WAR_TIME = 'Czas wojny',
      WEIGHT_OF_ALL_BAA = 'Waga środków bojowych',
      VERSION = 'v.0.1',
      YES = 'TAK';
}
